### ISSUE TITLE
Feature request: use python datetime objects

### ISSUE THREAD

**Issue by aebrahim** [stevepeak/timestring#28]
These objects are often expected when times and dates are required, and will make it easier to use timestring with other libraries.

**Comment by stevepeak** [comment]
This may be implemented already via:

```python
timestring.Date('now').date
>> datetime(...)
```

**Comment by aebrahim** [comment]
Thanks. I wasn't aware of that at the time.

I really like timestring. Thanks for writing it.

**Comment by stevepeak** [comment]
Your welcome! I really would like to clean the project up and make it faster but I have limited time these days. Cheers!
